### ISSUE TITLE
Blogging with Emacs

### ISSUE THREAD

**Issue by OrionRandD** [DiegoVicen/my-emacs#1]
hi,
I've read your post about blogging with Emacs.
https://diego.codes/post/blogging-with-org/
Could you point me to your org-publish blog configuration?
I cannot see it here in your configs...
Thx a ton

**Comment by diego-vicente** [comment]
You can find it in the old commits of the repo, for example [here][1] you can find it.

I'll go ahead and close this since it is not an issue.


[1]: https://github.com/diego-vicente/dvm-emacs/blob/1522d829098a06490db2d30522381c4d64bf2944/init-org.el#L114-L164
